### PR TITLE
Fix invalid memory read during compass initialisation

### LINKED ISSUE #581: Invalid read of memory during hmc5883 compass initialisation
The function [detectMag()](https://github.com/cleanflight/cleanflight/blob/94e499f9aae8b7f36568bd949b841503f89394ea/src/main/sensors/initialisation.c#L455) is called from `intialisation.c` to detect which magnetometer is in use. On the Naze, this function creates a nazeHmc5883Config on the stack and passes the address of this structure to [hmc5883lDetect()](https://github.com/cleanflight/cleanflight/blob/94e499f9aae8b7f36568bd949b841503f89394ea/src/main/drivers/compass_hmc5883l.c#L118). `hmc5883lDetect()` then stores that address into its global `hmc5883Config` variable.

But then the `detectMag()` function *returns*. Now that pointer to its stack memory is an invalid pointer: it has already returned so the `nazeHmc5883Config` is no longer available.

Later on, [compass.c calls mag.init()](https://github.com/cleanflight/cleanflight/blob/94e499f9aae8b7f36568bd949b841503f89394ea/src/main/sensors/compass.c#L55) which calls [hmc5883lInit()](https://github.com/cleanflight/cleanflight/blob/94e499f9aae8b7f36568bd949b841503f89394ea/src/main/drivers/compass_hmc5883l.c#L135). This function tries to read from the hmc5883Config pointer, which now just points to garbage on the stack.

This apparently works by chance in current builds, but on GCC 4.8 if you use -Os optimisation but disable link-time optimisation, a segfault occurs. `hmc5883lDetect()` sees this content of the config when it is first called:

```c
{gpioAPB2Peripherals = 16, gpioPin = 16384, gpioPort = 0x40011000}
```

But later on when `hmc5883lInit` is called, that data has been trashed to:

```c
{gpioAPB2Peripherals = 134282375, gpioPin = 64456, gpioPort = 0x81000000}
```

### PR DESCRIPTION
**Pull request by thenickdude**
Fixes #581

### CODE REVIEW

File: src/main/sensors/initialisation.c [hunk 1]
```diff
@@ -457,10 +457,10 @@ static void detectMag(magSensor_e magHardwareToUse)
     magSensor_e magHardware;
 
 #ifdef USE_MAG_HMC5883
-    static hmc5883Config_t *hmc5883Config = 0;
+    hmc5883Config_t *hmc5883Config = 0;
 
 #ifdef NAZE
-    hmc5883Config_t nazeHmc5883Config;
+    static hmc5883Config_t nazeHmc5883Config;
```
Comment (ledvinap) [inline src/main/sensors/initialisation.c]: It would be probably better to use
```
static const hmc5883Config_t nazeHmc5883Config_v1_4 = { ... };
static const hmc5883Config_t nazeHmc5883Config_v5 = { ... };
```
and modify rest of the code (add const to hmc5883lDetect parameter). But that is only cosmetic improvement.

**Comment by ledvinap** [comment]
Great catch !

File: src/main/sensors/initialisation.c (hunk 1 above)
Comment (thenickdude) [inline src/main/sensors/initialisation.c]: Good idea! That actually saves 12 bytes of BSS since the struct becomes const static instead of mutable.

**Comment by hydra** [comment]
hahah, lol nick - i just did it too, let me compare....
